services:
  server0:
    image: alpine/socat:latest
    init: true
    entrypoint: []
    command: [sh, -c, "sleep 600 && socat TCP-LISTEN:8000,reuseaddr,fork stdout"]

  server1:
    image: alpine/socat:latest
    init: true
    entrypoint: []
    command: [sh, -c, "sleep 605 && socat TCP-LISTEN:8000,reuseaddr,fork stdout"]

  server2:
    image: alpine/socat:latest
    init: true
    entrypoint: []
    command: [sh, -c, "sleep 610 && socat TCP-LISTEN:8000,reuseaddr,fork stdout"]

  server3:
    image: alpine/socat:latest
    init: true
    entrypoint: []
    command: [sh, -c, "sleep 615 && socat TCP-LISTEN:8000,reuseaddr,fork stdout"]

  tcpw:
    image: alpine:latest
    volumes:
      - ./x86_64/tcpw/tcpw:/usr/local/bin/tcpw:ro
    entrypoint: [tcpw, -t, 620s, -v, -a, server0:8000, -a, server1:8000, -a, server2:8000, -a, server3:8000]
    command: [echo, Done]
