#!/bin/bash
set -e

NAME=tcpw
ARGS="$@"

build() {
  go build -ldflags="-s -w" $ARGS -trimpath -o $1
  ./upx --8086 $1
}

export CGO_ENABLED=0
export GOOS=linux

GOARCH=amd64 build amd64/$NAME/$NAME
GOARCH=arm64 build arm64/$NAME/$NAME
GOARCH=arm GOARM=7 build armv7l/$NAME/$NAME