#!/bin/bash
set -e

NAME=tcpw
ARGS="$@"

build() {
  go build -ldflags="-s -w" $ARGS -trimpath -o $1
  ./upx --8086 $1
}

export CGO_ENABLED=0
export GOOS=linux

GOARCH=amd64 build bin/x86_64/$NAME
GOARCH=arm64 build bin/aarch64/$NAME
GOARCH=arm GOARM=7 build bin/armv7l/$NAME